#!/bin/bash

AWKCMD='
BEGIN { i=0; } {
if (i==0) {a=$1;b=$2;c=$3;} else
if (i==1) {d=$1;e=$2;f=$3;} else
if (i==2) {g=$1;h=$2;I=$3;}
i++; }
END {
det=a*e*I+b*f*g+c*d*h-a*f*h-b*d*I-c*e*g;
printf("%f\n",1/det);}
'

sed -e '1,/Linear_Transform =/d' $1 | awk -f<(echo "$AWKCMD")
